
"""
Constants module for AstroBin Upload Utility.
Defines central FITS keywords, configuration labels, and internal column names
to eliminate magic strings and ensure project-wide consistency.
"""

class FITSKeywords:
    """Standard FITS/XISF header keywords."""
    IMAGE_TYPE = 'IMAGETYP'
    EXPOSURE = 'EXPOSURE'
    DATE_OBS = 'DATE-OBS'
    XBINNING = 'XBINNING'
    GAIN = 'GAIN'
    EGAIN = 'EGAIN'
    INSTRUMENT = 'INSTRUME'
    TELESCOPE = 'TELESCOP'
    FOCUSER = 'FOCNAME'
    FILTER_WHEEL = 'FWHEEL'
    ROTATOR_NAME = 'ROTNAME'
    ROTATOR_ANGLE = 'ROTANTANG'
    PIXEL_SIZE = 'XPIXSZ'
    CCD_TEMP = 'CCD-TEMP'
    FOCAL_LENGTH = 'FOCALLEN'
    FOCAL_RATIO = 'FOCRATIO'
    SITE = 'SITE'
    SITE_LAT = 'SITELAT'
    SITE_LONG = 'SITELONG'
    BORTLE = 'BORTLE'
    SQM = 'SQM'
    FILTER = 'FILTER'
    OBJECT = 'OBJECT'
    FOCUSER_TEMP = 'FOCTEMP'
    HFR = 'HFR'
    FWHM = 'FWHM'
    SWCREATE = 'SWCREATE'
    FILENAME = 'FILENAME'
    NUMBER = 'NUMBER'
    IMSCALE = 'IMSCALE'

class ConfigKeys:
    """Labels used specifically in config.ini sections."""
    DEFAULTS = 'defaults'
    OVERRIDE = 'override'
    FILTERS = 'filters'
    SITES = 'sites'
    SECRET = 'secret'
    USE_OBS_DATE = 'USEOBSDATE'

class StandardizedKeys:
    """Lowercase versions of FITS keywords used after column standardization."""
    IMAGE_TYPE = 'imagetyp'
    EXPOSURE = 'exposure'
    DATE_OBS = 'date-obs'
    XBINNING = 'xbinning'
    GAIN = 'gain'
    EGAIN = 'egain'
    INSTRUMENT = 'instrume'
    TELESCOPE = 'telescop'
    FOCUSER = 'focname'
    FILTER_WHEEL = 'fwheel'
    ROTATOR_NAME = 'rotname'
    ROTATOR_ANGLE = 'rotantang'
    PIXEL_SIZE = 'xpixsz'
    CCD_TEMP = 'ccd-temp'
    FOCAL_LENGTH = 'focallen'
    FOCAL_RATIO = 'focratio'
    SITE = 'site'
    SITE_LAT = 'sitelat'
    SITE_LONG = 'sitelong'
    BORTLE = 'bortle'
    SQM = 'sqm'
    FILTER = 'filter'
    OBJECT = 'object'
    FOCUSER_TEMP = 'foctemp'
    HFR = 'hfr'
    FWHM = 'fwhm'
    SWCREATE = 'swcreate'
    FILENAME = 'filename'
    NUMBER = 'number'
    IMSCALE = 'imscale'

class InternalNames:
    """Internal column names used after normalization and aggregation."""
    IMAGE_TYPE = 'imageType'
    DURATION = 'duration'
    BINNING = 'binning'
    SENSOR_COOLING = 'sensorCooling'
    MEAN_FWHM = 'meanFwhm'
    F_NUMBER = 'fNumber'
    TEMPERATURE = 'temperature'
    FOCUSER = 'focuser'
    FILTER_WHEEL = 'filterWheel'
    TELESCOPE = 'telescope'
    CAMERA = 'camera'
    MEAN_SQM = 'meanSqm'
    FOCAL_LENGTH = 'focalLength'
    PIXEL_SIZE = 'pixelSize'
    TARGET = 'target'
    NUMBER = 'number'
    SESSIONS = 'sessions'
    START_DATE = 'start_date'
    END_DATE = 'end_date'
    NUM_DAYS = 'num_days'
    SITE_LAT = 'sitelat'
    SITE_LONG = 'sitelong'
    BORTLE = 'bortle'
    ROTATOR_NAME = 'rotname'
    ROTATOR_ANGLE = 'rotantang'

class ImageTypes:
    """Normalized Image Type values."""
    LIGHT = 'LIGHT'
    FLAT = 'FLAT'
    BIAS = 'BIAS'
    DARK = 'DARK'
    MASTER_LIGHT = 'MASTER LIGHT'
    MASTER_FLAT = 'MASTERFLAT'
    MASTER_DARK = 'MASTERDARK'
    MASTER_BIAS = 'MASTERBIAS'
    MASTER_DARKFLAT = 'MASTERDARKFLAT'
    DARK_FLAT = 'DARKFLAT'
