"""
Centralized constants for AstroBin Upload Utility v2.0.0.
"""

from enum import Enum

class FITSKeywords:
    IMAGE_TYPE = 'IMAGETYP'
    EXPOSURE = 'EXPOSURE'
    DATE_OBS = 'DATE-OBS'
    XBINNING = 'XBINNING'
    GAIN = 'GAIN'
    EGAIN = 'EGAIN'
    INSTRUMENT = 'INSTRUME'
    TELESCOPE = 'TELESCOP'
    FOCUSER = 'FOCNAME'
    FILTER_WHEEL = 'FWHEEL'
    ROTATOR_NAME = 'ROTNAME'
    ROTATOR_ANGLE = 'ROTANTANG'
    PIXEL_SIZE = 'XPIXSZ'
    CCD_TEMP = 'CCD-TEMP'
    FOCAL_LENGTH = 'FOCALLEN'
    FOCAL_RATIO = 'FOCRATIO'
    SITE = 'SITE'
    SITE_LAT = 'SITELAT'
    SITE_LONG = 'SITELONG'
    BORTLE = 'BORTLE'
    SQM = 'SQM'
    FILTER = 'FILTER'
    OBJECT = 'OBJECT'
    FOCUSER_TEMP = 'FOCTEMP'
    HFR = 'HFR'
    FWHM = 'FWHM'
    SWCREATE = 'SWCREATE'
    FILENAME = 'FILENAME'
    NUMBER = 'NUMBER'
    IMSCALE = 'IMSCALE'

class ConfigSections:
    DEFAULTS = 'defaults'
    OVERRIDE = 'override'
    FILTERS = 'filters'
    SITES = 'sites'
    SECRET = 'secret'

class InternalColumns:
    IMAGE_TYPE = 'imagetyp' 
    DURATION = 'exposure'
    BINNING = 'xbinning'
    SENSOR_COOLING = 'ccd-temp'
    MEAN_FWHM = 'fwhm'
    F_NUMBER = 'focratio'
    TEMPERATURE = 'foctemp'
    FOCUSER = 'focname'
    FILTER_WHEEL = 'fwheel'
    TELESCOPE = 'telescop'
    CAMERA = 'instrume'
    MEAN_SQM = 'sqm'
    FOCAL_LENGTH = 'focallen'
    PIXEL_SIZE = 'xpixsz'
    TARGET = 'object'
    SESSIONS = 'sessions'
    START_DATE = 'start_date'
    END_DATE = 'end_date'
    NUM_DAYS = 'num_days'
    SITE_LAT = 'sitelat'
    SITE_LONG = 'sitelong'
    BORTLE = 'bortle'
    ROTATOR_NAME = 'rotname'
    ROTATOR_ANGLE = 'rotantang'
    FILENAME = 'filename'
    NUMBER = 'number'
    DATE_OBS = 'date-obs'
    SITE_NAME = 'site'
    FILTER_NAME = 'filter'
    HFR = 'hfr'
    IMSCALE = 'imscale'
    GAIN = 'gain'
    EGAIN = 'egain'
    SWCREATE = 'swcreate'
    TEMP_MIN = 'temp_min'
    TEMP_MAX = 'temp_max'
    GAIN_MATCH = 'gain_match'

class ImageType(str, Enum):
    """Normalized Image Type values."""
    LIGHT = 'LIGHT'
    FLAT = 'FLAT'
    BIAS = 'BIAS'
    DARK = 'DARK'
    MASTER_LIGHT = 'MASTERLIGHT'
    MASTER_FLAT = 'MASTERFLAT'
    MASTER_DARK = 'MASTERDARK'
    MASTER_BIAS = 'MASTERBIAS'
    MASTER_DARKFLAT = 'MASTERDARKFLAT'
    DARK_FLAT = 'DARKFLAT'

# Backward compatibility aliases
InternalNames = InternalColumns
StandardizedKeys = InternalColumns 
ImageTypes = ImageType